// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/flutter.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiFlutterInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -840895270;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'fvcore',
        ioDirectory: '../fvcore/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiFlutterNativeCoreCancelDownloadTaskJson({
    required NativeCore that,
    required String id,
  });

  Future<void> crateApiFlutterNativeCoreDeleteDownloadTask({
    required NativeCore that,
    required String id,
  });

  Future<String> crateApiFlutterNativeCoreDownloadTaskJson({
    required NativeCore that,
    required String id,
  });

  Future<String> crateApiFlutterNativeCoreDownloadTasksJson({
    required NativeCore that,
  });

  Future<String> crateApiFlutterNativeCoreEhGalleryDetailJson({
    required NativeCore that,
    required String profile,
    required BigInt gid,
    required String token,
  });

  Future<String> crateApiFlutterNativeCoreEhSearchJson({
    required NativeCore that,
    required String profile,
    required String search,
    String? direction,
    BigInt? gid,
  });

  Future<String> crateApiFlutterNativeCoreEhThumbnailsJson({
    required NativeCore that,
    required String profile,
    required BigInt gid,
    required String token,
    required int page,
  });

  Future<String> crateApiFlutterNativeCoreEventsAfterJson({
    required NativeCore that,
    required BigInt cursor,
  });

  Future<Uint8List> crateApiFlutterNativeCoreImageResourceBytes({
    required NativeCore that,
    required String contentMd5,
    required String extension_,
  });

  Future<String> crateApiFlutterNativeCoreNextEventJson({
    required NativeCore that,
    required BigInt cursor,
  });

  Future<String> crateApiFlutterNativeCoreOperationJson({
    required NativeCore that,
    required String id,
  });

  Future<String> crateApiFlutterNativeCoreRetryDownloadTaskJson({
    required NativeCore that,
    required String id,
  });

  Future<String> crateApiFlutterNativeCoreRuntimeJson({
    required NativeCore that,
  });

  Future<void> crateApiFlutterNativeCoreShutdown({required NativeCore that});

  Future<String> crateApiFlutterNativeCoreStartEhPageFetchJson({
    required NativeCore that,
    required String profile,
    required BigInt gid,
    required String token,
    required int page,
  });

  Future<void> crateApiFlutterInitApp();

  Future<NativeCore> crateApiFlutterStartNativeCore({
    required String dataDir,
    required String cacheDir,
    required String downloadsDir,
    required String tempDir,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_NativeCore;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_NativeCore;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_NativeCorePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiFlutterNativeCoreCancelDownloadTaskJson({
    required NativeCore that,
    required String id,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeCore(
            that,
            serializer,
          );
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFlutterNativeCoreCancelDownloadTaskJsonConstMeta,
        argValues: [that, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFlutterNativeCoreCancelDownloadTaskJsonConstMeta =>
      const TaskConstMeta(
        debugName: "NativeCore_cancel_download_task_json",
        argNames: ["that", "id"],
      );

  @override
  Future<void> crateApiFlutterNativeCoreDeleteDownloadTask({
    required NativeCore that,
    required String id,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeCore(
            that,
            serializer,
          );
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFlutterNativeCoreDeleteDownloadTaskConstMeta,
        argValues: [that, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFlutterNativeCoreDeleteDownloadTaskConstMeta =>
      const TaskConstMeta(
        debugName: "NativeCore_delete_download_task",
        argNames: ["that", "id"],
      );

  @override
  Future<String> crateApiFlutterNativeCoreDownloadTaskJson({
    required NativeCore that,
    required String id,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeCore(
            that,
            serializer,
          );
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFlutterNativeCoreDownloadTaskJsonConstMeta,
        argValues: [that, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFlutterNativeCoreDownloadTaskJsonConstMeta =>
      const TaskConstMeta(
        debugName: "NativeCore_download_task_json",
        argNames: ["that", "id"],
      );

  @override
  Future<String> crateApiFlutterNativeCoreDownloadTasksJson({
    required NativeCore that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeCore(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFlutterNativeCoreDownloadTasksJsonConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFlutterNativeCoreDownloadTasksJsonConstMeta =>
      const TaskConstMeta(
        debugName: "NativeCore_download_tasks_json",
        argNames: ["that"],
      );

  @override
  Future<String> crateApiFlutterNativeCoreEhGalleryDetailJson({
    required NativeCore that,
    required String profile,
    required BigInt gid,
    required String token,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeCore(
            that,
            serializer,
          );
          sse_encode_String(profile, serializer);
          sse_encode_u_64(gid, serializer);
          sse_encode_String(token, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFlutterNativeCoreEhGalleryDetailJsonConstMeta,
        argValues: [that, profile, gid, token],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFlutterNativeCoreEhGalleryDetailJsonConstMeta =>
      const TaskConstMeta(
        debugName: "NativeCore_eh_gallery_detail_json",
        argNames: ["that", "profile", "gid", "token"],
      );

  @override
  Future<String> crateApiFlutterNativeCoreEhSearchJson({
    required NativeCore that,
    required String profile,
    required String search,
    String? direction,
    BigInt? gid,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeCore(
            that,
            serializer,
          );
          sse_encode_String(profile, serializer);
          sse_encode_String(search, serializer);
          sse_encode_opt_String(direction, serializer);
          sse_encode_opt_box_autoadd_u_64(gid, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFlutterNativeCoreEhSearchJsonConstMeta,
        argValues: [that, profile, search, direction, gid],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFlutterNativeCoreEhSearchJsonConstMeta =>
      const TaskConstMeta(
        debugName: "NativeCore_eh_search_json",
        argNames: ["that", "profile", "search", "direction", "gid"],
      );

  @override
  Future<String> crateApiFlutterNativeCoreEhThumbnailsJson({
    required NativeCore that,
    required String profile,
    required BigInt gid,
    required String token,
    required int page,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeCore(
            that,
            serializer,
          );
          sse_encode_String(profile, serializer);
          sse_encode_u_64(gid, serializer);
          sse_encode_String(token, serializer);
          sse_encode_u_32(page, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFlutterNativeCoreEhThumbnailsJsonConstMeta,
        argValues: [that, profile, gid, token, page],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFlutterNativeCoreEhThumbnailsJsonConstMeta =>
      const TaskConstMeta(
        debugName: "NativeCore_eh_thumbnails_json",
        argNames: ["that", "profile", "gid", "token", "page"],
      );

  @override
  Future<String> crateApiFlutterNativeCoreEventsAfterJson({
    required NativeCore that,
    required BigInt cursor,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeCore(
            that,
            serializer,
          );
          sse_encode_u_64(cursor, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFlutterNativeCoreEventsAfterJsonConstMeta,
        argValues: [that, cursor],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFlutterNativeCoreEventsAfterJsonConstMeta =>
      const TaskConstMeta(
        debugName: "NativeCore_events_after_json",
        argNames: ["that", "cursor"],
      );

  @override
  Future<Uint8List> crateApiFlutterNativeCoreImageResourceBytes({
    required NativeCore that,
    required String contentMd5,
    required String extension_,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeCore(
            that,
            serializer,
          );
          sse_encode_String(contentMd5, serializer);
          sse_encode_String(extension_, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFlutterNativeCoreImageResourceBytesConstMeta,
        argValues: [that, contentMd5, extension_],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFlutterNativeCoreImageResourceBytesConstMeta =>
      const TaskConstMeta(
        debugName: "NativeCore_image_resource_bytes",
        argNames: ["that", "contentMd5", "extension_"],
      );

  @override
  Future<String> crateApiFlutterNativeCoreNextEventJson({
    required NativeCore that,
    required BigInt cursor,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeCore(
            that,
            serializer,
          );
          sse_encode_u_64(cursor, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFlutterNativeCoreNextEventJsonConstMeta,
        argValues: [that, cursor],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFlutterNativeCoreNextEventJsonConstMeta =>
      const TaskConstMeta(
        debugName: "NativeCore_next_event_json",
        argNames: ["that", "cursor"],
      );

  @override
  Future<String> crateApiFlutterNativeCoreOperationJson({
    required NativeCore that,
    required String id,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeCore(
            that,
            serializer,
          );
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFlutterNativeCoreOperationJsonConstMeta,
        argValues: [that, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFlutterNativeCoreOperationJsonConstMeta =>
      const TaskConstMeta(
        debugName: "NativeCore_operation_json",
        argNames: ["that", "id"],
      );

  @override
  Future<String> crateApiFlutterNativeCoreRetryDownloadTaskJson({
    required NativeCore that,
    required String id,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeCore(
            that,
            serializer,
          );
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFlutterNativeCoreRetryDownloadTaskJsonConstMeta,
        argValues: [that, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFlutterNativeCoreRetryDownloadTaskJsonConstMeta =>
      const TaskConstMeta(
        debugName: "NativeCore_retry_download_task_json",
        argNames: ["that", "id"],
      );

  @override
  Future<String> crateApiFlutterNativeCoreRuntimeJson({
    required NativeCore that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeCore(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFlutterNativeCoreRuntimeJsonConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFlutterNativeCoreRuntimeJsonConstMeta =>
      const TaskConstMeta(
        debugName: "NativeCore_runtime_json",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiFlutterNativeCoreShutdown({required NativeCore that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeCore(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFlutterNativeCoreShutdownConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFlutterNativeCoreShutdownConstMeta =>
      const TaskConstMeta(debugName: "NativeCore_shutdown", argNames: ["that"]);

  @override
  Future<String> crateApiFlutterNativeCoreStartEhPageFetchJson({
    required NativeCore that,
    required String profile,
    required BigInt gid,
    required String token,
    required int page,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeCore(
            that,
            serializer,
          );
          sse_encode_String(profile, serializer);
          sse_encode_u_64(gid, serializer);
          sse_encode_String(token, serializer);
          sse_encode_u_32(page, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFlutterNativeCoreStartEhPageFetchJsonConstMeta,
        argValues: [that, profile, gid, token, page],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFlutterNativeCoreStartEhPageFetchJsonConstMeta =>
      const TaskConstMeta(
        debugName: "NativeCore_start_eh_page_fetch_json",
        argNames: ["that", "profile", "gid", "token", "page"],
      );

  @override
  Future<void> crateApiFlutterInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFlutterInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFlutterInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<NativeCore> crateApiFlutterStartNativeCore({
    required String dataDir,
    required String cacheDir,
    required String downloadsDir,
    required String tempDir,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dataDir, serializer);
          sse_encode_String(cacheDir, serializer);
          sse_encode_String(downloadsDir, serializer);
          sse_encode_String(tempDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeCore,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFlutterStartNativeCoreConstMeta,
        argValues: [dataDir, cacheDir, downloadsDir, tempDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFlutterStartNativeCoreConstMeta =>
      const TaskConstMeta(
        debugName: "start_native_core",
        argNames: ["dataDir", "cacheDir", "downloadsDir", "tempDir"],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_NativeCore => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeCore;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_NativeCore => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeCore;

  @protected
  NativeCore
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeCore(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return NativeCoreImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  NativeCore
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeCore(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return NativeCoreImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  NativeCore
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeCore(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return NativeCoreImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  NativeCore
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeCore(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return NativeCoreImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  NativeCore
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeCore(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return NativeCoreImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  NativeCore
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeCore(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return NativeCoreImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeCore(
    NativeCore self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as NativeCoreImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeCore(
    NativeCore self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as NativeCoreImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeCore(
    NativeCore self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as NativeCoreImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}

@sealed
class NativeCoreImpl extends RustOpaque implements NativeCore {
  // Not to be used by end users
  NativeCoreImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  NativeCoreImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_NativeCore,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_NativeCore,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_NativeCorePtr,
  );

  /// Cancels one persistent download task and returns its updated JSON view.
  Future<String> cancelDownloadTaskJson({required String id}) => RustLib
      .instance
      .api
      .crateApiFlutterNativeCoreCancelDownloadTaskJson(that: this, id: id);

  /// Deletes one terminal download task record when the owning family allows it.
  Future<void> deleteDownloadTask({required String id}) => RustLib.instance.api
      .crateApiFlutterNativeCoreDeleteDownloadTask(that: this, id: id);

  /// Returns one unified persistent download task as JSON.
  Future<String> downloadTaskJson({required String id}) => RustLib.instance.api
      .crateApiFlutterNativeCoreDownloadTaskJson(that: this, id: id);

  /// Returns unified persistent download tasks as JSON.
  Future<String> downloadTasksJson() => RustLib.instance.api
      .crateApiFlutterNativeCoreDownloadTasksJson(that: this);

  /// Returns parsed metadata for one EH gallery as JSON.
  Future<String> ehGalleryDetailJson({
    required String profile,
    required BigInt gid,
    required String token,
  }) => RustLib.instance.api.crateApiFlutterNativeCoreEhGalleryDetailJson(
    that: this,
    profile: profile,
    gid: gid,
    token: token,
  );

  /// Searches one EH profile and returns a listing page as JSON.
  Future<String> ehSearchJson({
    required String profile,
    required String search,
    String? direction,
    BigInt? gid,
  }) => RustLib.instance.api.crateApiFlutterNativeCoreEhSearchJson(
    that: this,
    profile: profile,
    search: search,
    direction: direction,
    gid: gid,
  );

  /// Returns one page of EH thumbnails as JSON.
  Future<String> ehThumbnailsJson({
    required String profile,
    required BigInt gid,
    required String token,
    required int page,
  }) => RustLib.instance.api.crateApiFlutterNativeCoreEhThumbnailsJson(
    that: this,
    profile: profile,
    gid: gid,
    token: token,
    page: page,
  );

  /// Replays retained Runtime events after a cursor as JSON.
  Future<String> eventsAfterJson({required BigInt cursor}) => RustLib
      .instance
      .api
      .crateApiFlutterNativeCoreEventsAfterJson(that: this, cursor: cursor);

  /// Reads content-addressed image bytes.
  Future<Uint8List> imageResourceBytes({
    required String contentMd5,
    required String extension_,
  }) => RustLib.instance.api.crateApiFlutterNativeCoreImageResourceBytes(
    that: this,
    contentMd5: contentMd5,
    extension_: extension_,
  );

  /// Waits for the next replayed or live event and returns its JSON envelope.
  Future<String> nextEventJson({required BigInt cursor}) => RustLib.instance.api
      .crateApiFlutterNativeCoreNextEventJson(that: this, cursor: cursor);

  /// Returns one operation snapshot as JSON.
  Future<String> operationJson({required String id}) => RustLib.instance.api
      .crateApiFlutterNativeCoreOperationJson(that: this, id: id);

  /// Retries one persistent download task and returns its updated JSON view.
  Future<String> retryDownloadTaskJson({required String id}) => RustLib
      .instance
      .api
      .crateApiFlutterNativeCoreRetryDownloadTaskJson(that: this, id: id);

  /// Returns a stable JSON Runtime snapshot.
  Future<String> runtimeJson() =>
      RustLib.instance.api.crateApiFlutterNativeCoreRuntimeJson(that: this);

  /// Requests graceful shutdown and waits for owned services to stop.
  Future<void> shutdown() =>
      RustLib.instance.api.crateApiFlutterNativeCoreShutdown(that: this);

  /// Starts one EH web-viewer page image fetch and returns the operation as JSON.
  Future<String> startEhPageFetchJson({
    required String profile,
    required BigInt gid,
    required String token,
    required int page,
  }) => RustLib.instance.api.crateApiFlutterNativeCoreStartEhPageFetchJson(
    that: this,
    profile: profile,
    gid: gid,
    token: token,
    page: page,
  );
}
