name: fletviewer_frontend
description: Experimental Flutter GUI for the standalone fvcore Runtime.
publish_to: none
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: 2.12.0
  fvcore:
    path: rust_builder
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
