// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `bridge_error`, `ensure_running`, `parse_eh_archive_variant`, `parse_eh_cursor`, `parse_operation_id`, `parse_pixiv_bookmark_visibility`, `parse_pixiv_following_visibility`, `parse_uuid`, `serialization_error`, `to_json`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BridgeError`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Starts one embedded Runtime using explicit platform storage paths.
Future<NativeCore> startNativeCore({
  required String dataDir,
  required String cacheDir,
  required String downloadsDir,
  required String tempDir,
}) => RustLib.instance.api.crateApiFlutterStartNativeCore(
  dataDir: dataDir,
  cacheDir: cacheDir,
  downloadsDir: downloadsDir,
  tempDir: tempDir,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NativeCore>>
abstract class NativeCore implements RustOpaqueInterface {
  /// Cancels one persistent download task and returns its updated JSON view.
  Future<String> cancelDownloadTaskJson({required String id});

  /// Clears all recorded browse history.
  Future<void> clearHistory();

  /// Saves one provider-scoped favorite search and returns it as JSON.
  Future<String> createFavoriteSearchJson({
    required String provider,
    required String profile,
    required String name,
    required String query,
  });

  /// Deletes one terminal download task record when the owning family allows it.
  Future<void> deleteDownloadTask({required String id});

  /// Deletes one favorite search by ID.
  Future<bool> deleteFavoriteSearchJson({required String id});

  /// Returns one unified persistent download task as JSON.
  Future<String> downloadTaskJson({required String id});

  /// Returns unified persistent download tasks as JSON.
  Future<String> downloadTasksJson();

  /// Returns official EH Archive options for one gallery as JSON.
  Future<String> ehArchiveOptionsJson({
    required String profile,
    required BigInt gid,
    required String token,
  });

  /// Returns the authenticated EH favorites listing for one profile as JSON.
  Future<String> ehFavoritesJson({required String profile});

  /// Returns parsed metadata for one EH gallery as JSON.
  Future<String> ehGalleryDetailJson({
    required String profile,
    required BigInt gid,
    required String token,
  });

  /// Returns the EH popular listing for one profile as JSON.
  Future<String> ehPopularJson({required String profile});

  /// Searches one EH profile and returns a listing page as JSON.
  Future<String> ehSearchJson({
    required String profile,
    required String search,
    String? direction,
    BigInt? gid,
  });

  /// Returns one page of EH thumbnails as JSON.
  Future<String> ehThumbnailsJson({
    required String profile,
    required BigInt gid,
    required String token,
    required int page,
  });

  /// Replays retained Runtime events after a cursor as JSON.
  Future<String> eventsAfterJson({required BigInt cursor});

  /// Lists provider-scoped favorite searches as JSON.
  Future<String> favoriteSearchesJson();

  /// Returns recent browse history as JSON.
  Future<String> historyJson();

  /// Reads content-addressed image bytes.
  Future<Uint8List> imageResourceBytes({
    required String contentMd5,
    required String extension_,
  });

  /// Waits for the next replayed or live event and returns its JSON envelope.
  Future<String> nextEventJson({required BigInt cursor});

  /// Returns one operation snapshot as JSON.
  Future<String> operationJson({required String id});

  /// Returns one authenticated Pixiv bookmark slice as JSON.
  Future<String> pixivBookmarksJson({
    required String profile,
    required String visibility,
    required int offset,
  });

  /// Returns one authenticated Pixiv following feed page as JSON.
  Future<String> pixivFollowingJson({
    required String profile,
    required String visibility,
    required int page,
  });

  /// Returns parsed metadata for one Pixiv illustration as JSON.
  Future<String> pixivIllustJson({
    required String profile,
    required String illustId,
  });

  /// Returns one Pixiv ranking page as JSON.
  Future<String> pixivRankingJson({
    required String profile,
    required String mode,
    required String date,
    required int page,
  });

  /// Returns the current Pixiv discovery recommendations as JSON.
  Future<String> pixivRecommendationsJson({required String profile});

  /// Searches one Pixiv profile and returns a result page as JSON.
  Future<String> pixivSearchJson({
    required String profile,
    required String query,
    required int page,
  });

  /// Retries one persistent download task and returns its updated JSON view.
  Future<String> retryDownloadTaskJson({required String id});

  /// Returns a stable JSON Runtime snapshot.
  Future<String> runtimeJson();

  /// Requests graceful shutdown and waits for owned services to stop.
  Future<void> shutdown();

  /// Starts one EH Archive download task and returns the task snapshot as JSON.
  Future<String> startEhArchiveDownloadJson({
    required String profile,
    required BigInt gid,
    required String token,
    required String variant,
  });

  /// Starts one EH gallery cover fetch and returns the operation as JSON.
  Future<String> startEhCoverFetchJson({
    required String profile,
    required BigInt gid,
    required String token,
  });

  /// Starts one EH web-viewer page image fetch and returns the operation as JSON.
  Future<String> startEhPageFetchJson({
    required String profile,
    required BigInt gid,
    required String token,
    required int page,
  });

  /// Starts one EH gallery thumbnail fetch and returns the operation as JSON.
  Future<String> startEhThumbnailFetchJson({
    required String profile,
    required BigInt gid,
    required String token,
    required int page,
    required String imageUrl,
  });

  /// Starts one Pixiv original page fetch and returns the operation as JSON.
  Future<String> startPixivPageFetchJson({
    required String profile,
    required String illustId,
    required int page,
  });

  /// Starts one Pixiv thumbnail fetch and returns the operation as JSON.
  Future<String> startPixivThumbnailFetchJson({
    required String profile,
    required String illustId,
    required int page,
    required String imageUrl,
  });

  /// Replaces one profile Cookie (or clears it) and returns the profile as JSON.
  Future<String> updateProfileCookieJson({
    required String provider,
    required String profile,
    String? cookie,
  });
}
