// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `bridge_error`, `ensure_running`, `parse_eh_cursor`, `parse_operation_id`, `parse_uuid`, `serialization_error`, `to_json`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BridgeError`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Starts one embedded Runtime using explicit platform storage paths.
Future<NativeCore> startNativeCore({
  required String dataDir,
  required String cacheDir,
  required String downloadsDir,
  required String tempDir,
}) => RustLib.instance.api.crateApiFlutterStartNativeCore(
  dataDir: dataDir,
  cacheDir: cacheDir,
  downloadsDir: downloadsDir,
  tempDir: tempDir,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NativeCore>>
abstract class NativeCore implements RustOpaqueInterface {
  /// Cancels one persistent download task and returns its updated JSON view.
  Future<String> cancelDownloadTaskJson({required String id});

  /// Deletes one terminal download task record when the owning family allows it.
  Future<void> deleteDownloadTask({required String id});

  /// Returns one unified persistent download task as JSON.
  Future<String> downloadTaskJson({required String id});

  /// Returns unified persistent download tasks as JSON.
  Future<String> downloadTasksJson();

  /// Returns parsed metadata for one EH gallery as JSON.
  Future<String> ehGalleryDetailJson({
    required String profile,
    required BigInt gid,
    required String token,
  });

  /// Searches one EH profile and returns a listing page as JSON.
  Future<String> ehSearchJson({
    required String profile,
    required String search,
    String? direction,
    BigInt? gid,
  });

  /// Returns one page of EH thumbnails as JSON.
  Future<String> ehThumbnailsJson({
    required String profile,
    required BigInt gid,
    required String token,
    required int page,
  });

  /// Replays retained Runtime events after a cursor as JSON.
  Future<String> eventsAfterJson({required BigInt cursor});

  /// Reads content-addressed image bytes.
  Future<Uint8List> imageResourceBytes({
    required String contentMd5,
    required String extension_,
  });

  /// Waits for the next replayed or live event and returns its JSON envelope.
  Future<String> nextEventJson({required BigInt cursor});

  /// Returns one operation snapshot as JSON.
  Future<String> operationJson({required String id});

  /// Retries one persistent download task and returns its updated JSON view.
  Future<String> retryDownloadTaskJson({required String id});

  /// Returns a stable JSON Runtime snapshot.
  Future<String> runtimeJson();

  /// Requests graceful shutdown and waits for owned services to stop.
  Future<void> shutdown();

  /// Starts one EH web-viewer page image fetch and returns the operation as JSON.
  Future<String> startEhPageFetchJson({
    required String profile,
    required BigInt gid,
    required String token,
    required int page,
  });
}
